### ISSUE TITLE
More a question than issue :)

### ISSUE THREAD

**Issue by wieluk** [pcwii/cpkodi-skill#17]
Hey thanks for the skill I am just curious if echo cancellation works for kodi. I have kodi connected to the same pi but with hdmi. Mycroft on analog audio. But i can’t tell mycroft commands like pause or noise down most of the time because the tv close to the mic.

**Comment by pcwii** [comment]
Mycroft does not have built in echo cancellation to my knowledge. There are quite a few discussions on the mycroft forum around echo cancellation where some people utilize the respeaker hardware and such. I do not run kodi and mycroft on the same hardware but I still have the issue if it is a noisy room due to music / movies playing. The new hardware platform for mycroft should address some of these issues.

**Comment by wieluk** [comment]
Thanks for your answer
